# Use docker-based infrastructure
sudo: false

language: java

jdk:
  - oraclejdk8

node_js: "0.12"

cache:
  directories:
    - "$HOME/.m2/repository"

before_install: npm install -g bower

install: /bin/true

script:
  - mvn -q -B -T 2 -U -Pstaging,javadoc,compatibility install jacoco:report
  - mvn -q -B coveralls:report -DrepoToken=$COVERALLS_TOKEN

after_success:
  - echo "<settings><servers><server><id>sonatype-nexus-snapshots</id><username>\${env.SONATYPE_USER}</username><password>\${env.SONATYPE_PASS}</password></server></servers></settings>" > ~/settings.xml
  - "[[ $TRAVIS_PULL_REQUEST == \"false\" && $TRAVIS_BRANCH == \"master\" ]] && mvn -q deploy --settings ~/settings.xml -DskipTests=true -Pjavadoc"
