sudo: false

language: java

jdk: oraclejdk8

node_js: "0.12"

before_install: npm install -g bower

notifications:
  irc: "chat.freenode.net#seedstack-dev"
  
cache:
  directories:
    - "$HOME/.m2/repository"

install: /bin/true

script:
  - mvn -B -U -T 4 -Pjavadoc install jacoco:report
#  - mvn -B coveralls:report -DrepoToken=$COVERALLS_TOKEN

after_success:
  - echo "<settings><servers><server><id>sonatype-nexus-snapshots</id><username>\${env.SONATYPE_USER}</username><password>\${env.SONATYPE_PASS}</password></server></servers></settings>" > ~/settings.xml
  - "[[ $TRAVIS_PULL_REQUEST == \"false\" && $TRAVIS_BRANCH == \"master\" ]] && mvn deploy --settings ~/settings.xml -DskipTests=true -Dmaven.javadoc.skip=true"
